logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: root
    password: root
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/films
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect